# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
version=1.0.0-ornithe

maven_group=io.github.axolotlclient.oldanimations
archives_base_name=AxolotlClient-OldAnimations

minecraft_18=1.8.9

mappings_18=1.8.9+build.27

fabric_loader=0.16.14

osl=0.16.3
config=3.0.11
client=3.1.3
