name: Automated build

on: [push, pull_request]

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: Mod
          path: build/libs/*
