name: Automated build

on: [push, pull_request]

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
            cache-read-only: ${{ github.ref != 'refs/heads/multiversion' }}

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: AxolotlClient-OldAnimations-nightly
          path: build/libs/*.jar
